from pydantic import BaseModel, Field, field_validator
from datetime import datetime, timezone
from typing import Optional, List
from langchain_core.messages import BaseMessage


# ============================================================
# 🧠 AgentState Model
# ------------------------------------------------------------
# Represents the typed and validated state of the LinkedIn 
# content creation workflow. This model is used to track 
# every step in the AI agent’s pipeline — from topic 
# generation to post approval and publishing.
# ============================================================
class AgentState(BaseModel):
    """
    Typed, validated state for LinkedIn content creation workflow.
    -------------------------------------------------------------
    This class captures all essential data the AI agent maintains 
    throughout its operation (e.g., the current niche, post drafts, 
    approval status, timestamps, etc.).
    """

    # === Conversation Messages ===
    # Stores the list of LangChain message objects exchanged during workflow execution.
    messages: List[BaseMessage] = Field(default_factory=list)

    # === Niche/Category ===
    # The primary topic or niche selected for content generation (e.g., “AI Marketing”).
    niche: str

    # === Topic ===
    # The specific topic generated within the niche (e.g., “AI tools for digital marketers”).
    topic: Optional[str] = None

    # === Draft Post ===
    # The first version of the post content generated by the AI agent.
    post_draft: Optional[str] = None

    # === Approval Status ===
    # Indicates whether the post draft has been approved for publishing.
    is_approved: bool = False

    # === Final Post ===
    # The finalized version of the post (after approval and edits).
    final_post: Optional[str] = None

    # === Current Node ===
    # Represents the workflow node currently being executed 
    # (e.g., “topic_generator”, “content_refiner”, etc.).
    current_node: str = "topic_generator"

    # === Iteration Counter ===
    # Tracks the number of revision cycles the agent has performed 
    # (useful for controlling loops and refinement steps).
    iteration_count: int = 0

    # === Image Asset URN ===
    # Stores the LinkedIn image asset URN returned after uploading media.
    image_asset_urn: Optional[str] = None

    # === Start Timestamp ===
    # Automatically captures the time when the workflow begins.
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # === Finish Timestamp ===
    # Populated when the workflow successfully completes.
    finished_at: Optional[datetime] = None


    # ============================================================
    # 🧩 Field Validation
    # ------------------------------------------------------------
    # Ensures that the 'niche' field is not empty or whitespace-only.
    # Raises a ValueError if validation fails.
    # ============================================================
    @field_validator("niche")
    @classmethod
    def niche_not_empty(cls, v: str) -> str:
        """Ensure that the 'niche' field is not empty."""
        if not v or not v.strip():
            raise ValueError("niche must not be empty")
        return v
