from pydantic import BaseModel, Field
from datetime import datetime, timezone
from typing import Optional


# ============================================================
# 📝 Post Model
# ------------------------------------------------------------
# Represents a single social media post document to be stored 
# in MongoDB. Each post contains information such as:
# - The platform it was created for (LinkedIn, Facebook, etc.)
# - The actual post content (text)
# - Optional image data (binary)
# - A timestamp indicating when the post was created.
# ============================================================
class Post(BaseModel):
    """
    Data model for storing post content and metadata.
    -------------------------------------------------
    Used to represent posts generated and saved by the agent
    to the database. Each instance corresponds to one post.
    """

    # === Platform Name ===
    # Identifies the social media platform (e.g., "LinkedIn", "Facebook").
    platform: str = Field(
        ...,
        description="Platform name e.g., LinkedIn, Facebook"
    )

    # === Post Content ===
    # Contains the main body of the post text.
    content: str = Field(
        ...,
        description="Content of the post"
    )

    # === Image Data (Optional) ===
    # Stores binary image data (e.g., from Gemini AI image generation).
    # This field may be None if the post is text-only.
    image_data: Optional[bytes] = Field(
        None,
        description="Binary image data generated by Gemini"
    )

    # === Timestamp (UTC) ===
    # Automatically records the UTC time when the post object is created.
    # Helps with ordering and history tracking in the database.
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Post creation timestamp (UTC)"
    )

# ==============================================================
# 🔹 Request Body Model
#    Defines the structure for the POST /agent/start request
# ==============================================================

class NicheRequest(BaseModel):
    """
    Represents the input model for the agent workflow API.
    Example JSON: { "niche": "AI Marketing" }
    """
    niche: str
